# Copyright 2023 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "snitch"
authors = [
    {name = "Luca Colagrande", email = "colluca@iis.ee.ethz.ch"}
]
dynamic = ["version"]
dependencies = [
    # Keep sorted.
    # General dependencies.
    "bin2coe",
    "dataclasses",
    "editorconfig-checker==2.3.51",
    "flake8",
    "gitpython",
    "hjson",
    "humanize",
    "json5",
    "jsonref",
    "jsonschema",
    "mako",
    "matplotlib",
    "mkdocs-material",
    "pandas",
    "prettytable",
    "progressbar2",
    "psutil",
    "pyelftools",
    "pyflexfloat",
    "pytablewriter",
    "pytest",
    "pyyaml",
    "scikit-learn",
    "tabulate",
    "termcolor",
    "yamllint",
    # DNN lib dependencies.
    "numpy",
    "torch",
    "json5"
]

[project.optional-dependencies]
docs = [
    "mkdocs",
    "mkdocs-material",
    "mkdocs-include-markdown-plugin",
    "mkdocs-macros-plugin",
    "mkdocstrings",
    "mkdocstrings-python",
]

[tool.setuptools.package-dir]
"snitch.dnn" = "sw/dnn"
"snitch.blas" = "sw/blas"
"snitch.util" = "util"
