# Copyright 2020 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Run functional regression checks
name: ci
on:
  workflow_run:
      workflows: [build-docker]
      types: [completed]

jobs:

  ########
  # Docs #
  ########

  docs:
    name: Build documentation
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/pulp-platform/snitch_cluster:${{ github.ref_name }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Build docs
        run: make docs

  #####################
  # Python unit tests #
  #####################

  pytest:
    name: Python unit tests
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/pulp-platform/snitch_cluster:${{ github.ref_name }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Run pytest
        run: pytest

  ##############################################
  # Simulate SW on Snitch Cluster w/ Verilator #
  ##############################################

  sw-snitch-cluster-vlt:
    name: Simulate SW on Snitch Cluster w/ Verilator
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/pulp-platform/snitch_cluster:${{ github.ref_name }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Hash Verilator prerequisites
        id: verilator-hash
        uses: colluca/list-make-prerequisites@v1.0.1
        with:
          working-directory: target/snitch_cluster
          target: bin/snitch_cluster.vlt
          flags: --recursive
      - name: Set up cache for Verilator build
        id: verilator-cache
        uses: actions/cache@v3
        with:
          path: target/snitch_cluster/bin
          key: verilator-${{ steps.verilator-hash.outputs.hash }}
          restore-keys: |
            verilator-
      - name: Build Hardware
        if: steps.verilator-cache.outputs.cache-hit != 'true'
        working-directory: target/snitch_cluster
        run: |
          make CFG_OVERRIDE=cfg/github-ci.hjson VLT_JOBS=1 bin/snitch_cluster.vlt
      - name: Build Software
        working-directory: target/snitch_cluster
        run: |
          make CFG_OVERRIDE=cfg/github-ci.hjson sw
      - name: Run Tests
        working-directory: target/snitch_cluster
        run: |
          ./util/run.py sw/run.yaml --simulator verilator -j
          ./util/run.py sw/fdiv.yaml --simulator verilator -j
      - name: Annotate traces
        working-directory: target/snitch_cluster
        run: |
          make SIM_DIR=./runs/simple annotate -j

  #########################################
  # Build SW on Snitch Cluster w/ Banshee #
  #########################################

  sw-snitch-cluster-banshee:
    name: Simulate SW on Snitch Cluster w/ Banshee
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/pulp-platform/snitch_cluster:${{ github.ref_name }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build Software
        run: |
          bender vendor init
          make -C target/snitch_cluster SELECT_RUNTIME=banshee sw
      - name: Run Tests
        env:
          SNITCH_LOG: info
        working-directory: target/snitch_cluster
        run: |
          ./util/run.py sw/run.yaml --simulator banshee -j
